name: MTE
main: mte.main
author: MTE TEAM
version: 1.0.4

commands:
  teleport:
    usage: /<command>
    description: To teleport to other players
  mte:
    usage: /<command>
    description: Shows help menu
  execute:
    usage: /<command>
    description: To kill yourself